"""
Business Report Formatter for Professional Output
"""
from datetime import datetime
from typing import Dict, List, Any, Optional
import json


class BusinessReportFormatter:
    """
    Formats business insight cards into professional reports
    """

    def __init__(self):
        self.report_date = datetime.now().strftime("%B %d, %Y")
        self.report_time = datetime.now().strftime("%I:%M %p")

    def format_metric_card(self, title: str, calculation: str, example: str,
                          interpretation: str, recommendations: List[str] = None) -> str:
        """
        Format a single metric card into a professional report section
        """
        report = f"""
{'='*80}
{title.upper()}
{'='*80}

CALCULATION METHODOLOGY:
{calculation}

EXAMPLE CALCULATION:
{example}

ANALYSIS & INTERPRETATION:
{interpretation}
"""

        if recommendations:
            report += f"""
RECOMMENDATIONS:
"""
            for i, rec in enumerate(recommendations, 1):
                report += f"{i}. {rec}\n"

        report += f"""
{'='*80}
"""
        return report

    def format_comprehensive_report(self, title: str, metrics: List[Dict],
                                  executive_summary: str = None) -> str:
        """
        Format multiple metrics into a comprehensive business report
        """
        report = f"""
{'='*80}
BUSINESS INTELLIGENCE REPORT
{title.upper()}
{'='*80}

Report Date: {self.report_date}
Generated Time: {self.report_time}

"""

        if executive_summary:
            report += f"""
EXECUTIVE SUMMARY:
{executive_summary}

{'='*80}

"""

        for metric in metrics:
            report += self.format_metric_card(
                title=metric.get('title', 'Metric'),
                calculation=metric.get('calculation', ''),
                example=metric.get('example', ''),
                interpretation=metric.get('interpretation', ''),
                recommendations=metric.get('recommendations', [])
            )

        report += f"""
{'='*80}
END OF REPORT
{'='*80}

Generated by Hospitality AI Agent
For more insights, visit your dashboard or chat with our AI assistant.
"""

        return report

    def format_labor_analysis(self, labor_costs: float, total_sales: float,
                            labor_hours: float) -> str:
        """
        Format labor analysis into a professional report
        """
        labor_percentage = (labor_costs / total_sales) * 100 if total_sales > 0 else 0
        productivity = total_sales / labor_hours if labor_hours > 0 else 0

        metrics = [
            {
                'title': 'Labor Cost Percentage',
                'calculation': '(Total Labor Costs / Total Sales) × 100',
                'example': f'(${labor_costs:,.2f} / ${total_sales:,.2f}) × 100 = {labor_percentage:.1f}%',
                'interpretation': self._interpret_labor_percentage(labor_percentage),
                'recommendations': self._get_labor_recommendations(labor_percentage)
            },
            {
                'title': 'Labor Productivity',
                'calculation': 'Sales / Labor Hours',
                'example': f'${total_sales:,.2f} / {labor_hours:.0f} hours = ${productivity:.2f} per hour',
                'interpretation': self._interpret_productivity(productivity),
                'recommendations': self._get_productivity_recommendations(productivity)
            }
        ]

        executive_summary = f"""
Your restaurant's labor efficiency analysis shows a {labor_percentage:.1f}% labor cost ratio
and ${productivity:.2f} in sales per labor hour. {'This indicates strong operational efficiency' if labor_percentage < 20 else 'There are opportunities for optimization'}
in your labor management strategy.
"""

        return self.format_comprehensive_report("Labor Efficiency Analysis", metrics, executive_summary)

    def format_kpi_analysis(self, kpi_data: Dict[str, Any]) -> str:
        """
        Format KPI analysis into a professional report
        """
        metrics = []

        for kpi_name, kpi_info in kpi_data.items():
            metrics.append({
                'title': kpi_info.get('title', kpi_name),
                'calculation': kpi_info.get('calculation', ''),
                'example': kpi_info.get('example', ''),
                'interpretation': kpi_info.get('interpretation', ''),
                'recommendations': kpi_info.get('recommendations', [])
            })

        executive_summary = f"""
Comprehensive KPI analysis covering {len(metrics)} key performance indicators.
This report provides actionable insights to optimize your restaurant's operational efficiency.
"""

        return self.format_comprehensive_report("Key Performance Indicators Analysis", metrics, executive_summary)

    def format_inventory_analysis(self, inventory_data: Dict[str, Any]) -> str:
        """
        Format inventory analysis into a professional report
        """
        metrics = []

        for item, data in inventory_data.items():
            metrics.append({
                'title': f'Inventory Analysis - {item}',
                'calculation': data.get('calculation', ''),
                'example': data.get('example', ''),
                'interpretation': data.get('interpretation', ''),
                'recommendations': data.get('recommendations', [])
            })

        executive_summary = f"""
Inventory optimization analysis covering {len(metrics)} key inventory metrics.
This report helps identify cost-saving opportunities and improve inventory turnover.
"""

        return self.format_comprehensive_report("Inventory Optimization Analysis", metrics, executive_summary)

    def _interpret_labor_percentage(self, percentage: float) -> str:
        """Interpret labor cost percentage"""
        if percentage < 20:
            return f"A labor cost percentage of {percentage:.1f}% is considered excellent and indicates strong operational efficiency. This is well below industry standards of 20-30%."
        elif percentage < 25:
            return f"A labor cost percentage of {percentage:.1f}% is considered good and within acceptable range. This is slightly below industry standards of 20-30%."
        elif percentage < 30:
            return f"A labor cost percentage of {percentage:.1f}% is at the upper limit of industry standards (20-30%). Consider optimization strategies."
        else:
            return f"A labor cost percentage of {percentage:.1f}% exceeds industry standards (20-30%). Immediate action is recommended to improve labor efficiency."

    def _get_labor_recommendations(self, percentage: float) -> List[str]:
        """Get labor cost recommendations"""
        recommendations = []

        if percentage > 25:
            recommendations.extend([
                "Implement dynamic scheduling based on sales forecasts",
                "Cross-train staff to handle multiple roles during peak hours",
                "Review and optimize staff schedules to match business patterns",
                "Consider automation for repetitive tasks"
            ])
        else:
            recommendations.extend([
                "Maintain current efficiency levels",
                "Continue monitoring labor costs regularly",
                "Consider staff development programs to maintain quality"
            ])

        return recommendations

    def _interpret_productivity(self, productivity: float) -> str:
        """Interpret labor productivity"""
        if productivity > 50:
            return f"Labor productivity of ${productivity:.2f} per hour is excellent and indicates highly efficient operations."
        elif productivity > 30:
            return f"Labor productivity of ${productivity:.2f} per hour is good and shows effective labor utilization."
        elif productivity > 20:
            return f"Labor productivity of ${productivity:.2f} per hour is average. There's room for improvement in efficiency."
        else:
            return f"Labor productivity of ${productivity:.2f} per hour is below optimal. Immediate attention to labor efficiency is recommended."

    def _get_productivity_recommendations(self, productivity: float) -> List[str]:
        """Get productivity recommendations"""
        recommendations = []

        if productivity < 30:
            recommendations.extend([
                "Analyze peak hours and optimize staffing accordingly",
                "Implement performance tracking for individual staff members",
                "Review operational processes for efficiency improvements",
                "Consider staff training programs to improve productivity"
            ])
        else:
            recommendations.extend([
                "Maintain current productivity levels",
                "Continue monitoring and benchmarking against industry standards",
                "Share best practices across all shifts"
            ])

        return recommendations


def format_business_insight(title: str, calculation: str, example: str,
                          interpretation: str, recommendations: List[str] = None) -> str:
    """
    Convenience function to format a single business insight
    """
    formatter = BusinessReportFormatter()
    return formatter.format_metric_card(title, calculation, example, interpretation, recommendations)


def format_comprehensive_analysis(analysis_type: str, data: Dict[str, Any]) -> str:
    """
    Convenience function to format comprehensive analysis
    """
    formatter = BusinessReportFormatter()

    if analysis_type.lower() == 'labor':
        return formatter.format_labor_analysis(
            data.get('labor_costs', 0),
            data.get('total_sales', 0),
            data.get('labor_hours', 0)
        )
    elif analysis_type.lower() == 'kpi':
        return formatter.format_kpi_analysis(data)
    elif analysis_type.lower() == 'inventory':
        return formatter.format_inventory_analysis(data)
    else:
        # Generic comprehensive report
        metrics = []
        for key, value in data.items():
            if isinstance(value, dict):
                metrics.append(value)

        return formatter.format_comprehensive_report(f"{analysis_type.title()} Analysis", metrics)
